import os
from datetime import datetime

try:
    # import the helper from app if available
    from app import send_email_notification, init_db
except Exception:
    send_email_notification = None
    init_db = None


def main():
    if init_db:
        try:
            init_db()
        except Exception:
            pass
    to_addr = os.environ.get('ADMIN_EMAIL', 'test@example.com')
    subject = f'Test notification from vender.store at {datetime.utcnow().isoformat()}'
    body = 'This is a test notification generated by scripts/send_test_email.py'
    if send_email_notification:
        send_email_notification(to_addr, subject, body)
        print('Invoked send_email_notification (check logs for delivery/simulation).')
    else:
        print('send_email_notification helper not available; cannot send.')


if __name__ == '__main__':
    main()
